# Generated by Django 3.2.3 on 2021-06-28 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryTest',
            fields=[
                ('column1', models.AutoField(primary_key=True, serialize=False)),
                ('column2', models.IntegerField(blank=True, null=True)),
                ('column3', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'query_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipesRecipe',
            fields=[
                ('recipe_name', models.CharField(max_length=100)),
                ('serves', models.PositiveIntegerField()),
                ('date_submitted', models.DateTimeField()),
                ('description', models.TextField()),
                ('recipe_text', models.TextField()),
                ('calories', models.FloatField()),
                ('avg_rating', models.FloatField()),
                ('time_to_prepare', models.FloatField()),
                ('num_ratings', models.PositiveIntegerField()),
                ('img_url', models.CharField(max_length=200)),
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recipes_recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Samplecuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuisine_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'SampleCuisine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sampleingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.TextField()),
            ],
            options={
                'db_table': 'SampleIngredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sampleinteraction',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.user')),
                ('interaction_date', models.DateField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SampleInteraction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Samplerecipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=255)),
                ('serves', models.IntegerField()),
                ('date_submitted', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('recipe_text', models.TextField()),
                ('calories', models.FloatField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('time_to_prepare', models.IntegerField(blank=True, null=True)),
                ('num_ratings', models.IntegerField()),
                ('img_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SampleRecipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sampletag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_text', models.TextField()),
            ],
            options={
                'db_table': 'SampleTag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Samplerecipeingredient',
            fields=[
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recipes.samplerecipe')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('measurement_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SampleRecipeIngredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Samplerecipetag',
            fields=[
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recipes.samplerecipe')),
            ],
            options={
                'db_table': 'SampleRecipeTag',
                'managed': False,
            },
        ),
    ]
