# Generated by Django 3.2.3 on 2021-06-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuisine_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'SampleCuisine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.TextField()),
            ],
            options={
                'db_table': 'SampleIngredient',
                'managed': False,
            },
        ),
    ]
