# Generated by Django 3.2.3 on 2021-07-01 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.user')),
                ('interaction_date', models.DateField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Interaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=255)),
                ('serves', models.IntegerField()),
                ('date_submitted', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('recipe_text', models.TextField()),
                ('calories', models.FloatField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('time_to_prepare', models.IntegerField(blank=True, null=True)),
                ('num_ratings', models.IntegerField()),
                ('img_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_text', models.TextField()),
            ],
            options={
                'db_table': 'Tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipeingredient',
            fields=[
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recipes.recipe')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('measurement_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'RecipeIngredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipetag',
            fields=[
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recipes.recipe')),
            ],
            options={
                'db_table': 'RecipeTag',
                'managed': False,
            },
        ),
    ]
