# Generated by Django 3.2.3 on 2021-06-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210613_0515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'managed': False},
        ),
    ]
