-- This query creates a new recipe by:
--      retreiving the appropriate cuisineID from SampleCuisine table
--      inserting the recipe fields into the SampleRecipe table
--      inserting the appropriate recipe-ingredient tuple in RecipeIngredient
--      creating new tags (if any) in SampleTag
--      Adding recipe-tag tuples to SampleRecipeTag
-- "Indian" is considered user input from the recipe creation page
SET @cuisineID = (SELECT cuisine_id FROM SampleCuisine WHERE cuisine_name =
'Indian');

-- The following query will create a 'Palak Paneer' recipe and insert it into the SampleRecipe table, all values below will be user input from the recipe creation table
INSERT INTO SampleRecipe
            (creator_id,
             recipe_name,
             serves,
             date_submitted,
             cuisine_id,
             description,
             recipe_text,
             calories,
             time_to_prepare,
             img_url)
VALUES     (2,
            'Palak Paneer',
            1,
            '2020-01-02',
            @cuisineID,
            'green paneer dish',
            'recipe_here',
            350,
            50,
'https://www.mineralpro.com/assets/uploads/2015/09/bigstock-Washing-Colorful-Fruits-And-Ve-39688621.jpg'
);

SET @recipeID = (SELECT LAST_INSERT_ID());

-- These insert statements will be genereated by the python backend for each ingredient
-- 'spinach' is an incredient for the above recipe that is specified by the user during recipe creation
INSERT INTO SampleRecipeIngredient
            (recipe_id,
             ingredient_id,
             quantity,
             measurement_type)
VALUES      (@recipeID,
             (SELECT ingredient_id
              FROM   SampleIngredient
              WHERE  ingredient_name = "spinach"),
             2,
             'cups');

-- 'paneer' is an incredient for the above recipe that is specified by the user during recipe creation
INSERT INTO SampleRecipeIngredient
            (recipe_id,
             ingredient_id,
             quantity,
             measurement_type)
VALUES      (@recipeID,
             (SELECT ingredient_id
              FROM   SampleIngredient
              WHERE  ingredient_name = "paneer"),
             2,
             'cups');

-- These insert statements will be generated by the python backend for each tag
-- It is assumed that the user will tag the above recipe as 'vegetarian' during recipe creation
INSERT INTO SampleRecipeTag
            (recipe_id,
             tag_id)
VALUES      (@recipeID,
             (SELECT tag_id
              FROM   SampleTag
              WHERE  tag_text = "vegetarian"));

-- It is assumed that the user will tag the above recipe as 'spicy' during recipe creation
INSERT INTO SampleRecipeTag
            (recipe_id,
             tag_id)
VALUES      (@recipeID,
             (SELECT tag_id
              FROM   SampleTag
              WHERE  tag_text = "spicy")); 
