-- This query mimics the interaction queries generated by the backend that will fill the SampleInteraction table
-- Triggers have been set up in the create_sample_tables script that will update the SampleRecipe and SampleUser tables with the new rating and review


-- Below is a sample interaction where the user has rated a dish with a 5/5 and commented on the recipe
-- The values inserted represent user input
INSERT INTO SampleInteraction(user_id,recipe_id,interaction_date,rating,review)
VALUE (2,1,'2020-2-2', 5,'Wow super tasty, i love chicken')
