--This query mimics the interaction queries generated by the backend that will fill the SampleInteraction table
--Triggers have been set up in the create_sample_tables script that will update the SampleRecipe and SampleUser tables with the new rating and review

INSERT INTO SampleInteraction(user_id,recipe_id,interaction_date,rating,review)
VALUE (2,1,'2020-2-2', 3,'Wow super tasty, i love chicken')
