DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Recipe;
DROP TABLE IF EXISTS Ingredient;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS Interactions;
DROP TABLE IF EXISTS RecipeIngredients;
DROP TABLE IF EXISTS RecipeTag;
DROP TABLE IF EXISTS Cuisine;
