DROP TABLE IF EXISTS SampleRecipeTag;
DROP TABLE IF EXISTS SampleRecipeIngredient;
DROP TABLE IF EXISTS SampleInteraction;
DROP TABLE IF EXISTS SampleRecipe;
DROP TABLE IF EXISTS SampleUser;
DROP TABLE IF EXISTS SampleIngredient;
DROP TABLE IF EXISTS SampleTag;
DROP TABLE IF EXISTS SampleCuisine;
